import { ClientRecord, ClientComment } from './types';
import { getFormattedDate } from './mock-data';

export const INITIAL_CLIENT_RECORDS: ClientRecord[] = [
  {
    id: 'cli-1',
    userId: 'user-emp-5', // Aniket
    userName: 'Aniket',
    userTeam: 'DEMO_TEAM',
    date: getFormattedDate(0),
    activityType: 'demoDone',
    clientName: 'Nazir Jewellers',
    contactPerson: 'Nazir',
    mobile: '9876543210',
    city: 'Mumbai',
    status: 'Demo Completed',
    saleAmount: 450000,
    paymentStatus: 'Pending',
    notes: 'Demo completed successfully! Client interested in POS & RFID features.',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'cli-2',
    userId: 'user-emp-10', // Pratiksha
    userName: 'Pratiksha',
    userTeam: 'LEAD_MANAGEMENT',
    date: getFormattedDate(-1),
    activityType: 'firstCalls',
    clientName: 'Nazir Jewellers',
    contactPerson: 'Nazir',
    mobile: '9876543210',
    city: 'Mumbai',
    status: 'Lead Qualified & Demo Arranged',
    notes: 'Initial call done. Arranged demo for Aniket to present.',
    followUpDate: getFormattedDate(2),
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'cli-3',
    userId: 'user-emp-1', // Suraj
    userName: 'Suraj',
    userTeam: 'DEMO_TEAM',
    date: getFormattedDate(0),
    activityType: 'demoDone',
    clientName: 'Alankar Gold World',
    contactPerson: 'Rahul',
    mobile: '9876543211',
    city: 'Delhi',
    status: 'Demo Completed',
    notes: 'Completed full walkthrough of the billing module. Requested pricing details for 3 outlets.',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'cli-4',
    userId: 'user-emp-3', // Pavitra
    userName: 'Pavitra',
    userTeam: 'DEMO_TEAM',
    date: getFormattedDate(0),
    activityType: 'followUpCalls',
    clientName: 'SK Maidul Islam',
    contactPerson: 'Maidul',
    mobile: '9876543212',
    city: 'Kolkata',
    status: 'Interested',
    notes: 'Shared product catalog and price list on WhatsApp. Call again tomorrow.',
    followUpDate: getFormattedDate(1),
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: 'cli-5',
    userId: 'user-emp-11', // Ayush
    userName: 'Ayush',
    userTeam: 'LEAD_MANAGEMENT',
    date: getFormattedDate(-1),
    activityType: 'oldCalls',
    clientName: 'Kalyan Jewellers Franchisee',
    contactPerson: 'Satish Kumar',
    mobile: '9845112233',
    city: 'Bangalore',
    status: 'Demo Arranged',
    notes: 'Followed up on old lead, client agreed for demo presentation.',
    followUpDate: getFormattedDate(2),
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const INITIAL_CLIENT_COMMENTS: ClientComment[] = [
  {
    id: 'cc-1',
    mobile: '9876543210',
    userId: 'user-emp-10',
    userName: 'Pratiksha',
    userTeam: 'LEAD_MANAGEMENT',
    content: 'Client requested specific focus on multi-store inventory sync during demo.',
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: 'cc-2',
    mobile: '9876543210',
    userId: 'user-emp-5',
    userName: 'Aniket',
    userTeam: 'DEMO_TEAM',
    content: 'Thanks Pratiksha! Covered multi-store inventory in the demo. Client loved it, sending proposal now.',
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
];
